# .goreleaser.yml

project_name: get-kube

# Defines the builds to be done
builds:
- id: get-kube-linux
  main: ./cmd/get-kube/main.go
  binary: get-kube
  goos:
  - linux
  goarch:
  - amd64
  - arm64
  env:
  - CGO_ENABLED=0
  ldflags:
  - '-s -w'
- id: get-kube-macos
  main: ./cmd/get-kube/main.go
  binary: get-kube
  goos:
  - darwin
  goarch:
  - amd64
  - arm64
  env:
  - CGO_ENABLED=0
  ldflags:
  - '-s -w'
- id: get-kube-windows
  main: ./cmd/get-kube/main.go
  binary: get-kube.exe
  goos:
  - windows
  goarch:
  - amd64
  - arm64
  env:
  - CGO_ENABLED=0
  ldflags:
  - '-s -w'

# Defines the archives containing the binaries
archives:
- format: tar.gz
  name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}'
  files:
  - LICENSE
  - README.md
  - CHANGELOG.md
- format: zip
  name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}'
  files:
  - LICENSE
  - README.md

# Defines the snapshot (pre-release) strategy
snapshot:
  name_template: "{{ .Tag }}-next"

# Generates checksums for binaries
checksum:
  name_template: 'checksums.txt'

# Docker image creation is disabled
dockers: []

# Package managers like Brew and nfpm (disabled)
brews: []
# nfpm: []

# Release configuration
release:
  draft: false
  # prerelease: false
  name_template: "{{ .ProjectName }} v{{ .Version }}" # Release naming convention
